python ave_avvp.py \
--gpu 2 \
--lr 0.0004 \
--clip_gradient 0.5 \
--snapshot_pref "./Exps/ave_avvp/" \
--n_epoch 30 \
--b 80 \
--test_batch_size 64 \
--dataset_name "ave_avvp_va" \
--print_freq 1 \
--eval_freq 1