python ucf_oscmg.py \
--gpu 1 \
--lr 0.0004 \
--clip_gradient 0.5 \
--snapshot_pref "./Exps/ucf_oscmg/" \
--n_epoch 16 \
--b 80 \
--test_batch_size 64 \
--dataset_name "ucf_va" \
--print_freq 1 \
--eval_freq 1 \
--source_class_num 17