python pretrain_fc.py \
--gpu 3 \
--lr 0.0004 \
--clip_gradient 0.5 \
--snapshot_pref "./Exps/pretrain_fc/" \
--n_epoch 4 \
--b 80 \
--test_batch_size 64 \
--dataset_name "vggsound_AVT" \
--print_freq 1 \
--model_save_path "../checkpoints/fc/steps"